const Activity = require('../../database/models/activity')
const Submission = require('../../database/models/submission')
const HTTP_Error = require('../../utils/HTTP_Error')



async function get_activities(req, res, next) {
    try {
        // Find all the activities that need to be graded manually (of this event)
        const activitySets = await res.locals.event.getActivitySets({
            include: {
                model: Activity,
                attributes: ['id', 'name', 'pointValue'],
                where: {
                    gradingType: 'judge'
                }
            }
        })
        
        return res
            .status(200)
            .json(activitySets.activities)
    } catch (err) {
        return next(new HTTP_Error(500, 'unexpected error', err))
    }
}

async function get_participants(req, res, next) {
    try {
        // Lazy load the associated participants
        const participants = await res.locals.event.getParticipants({
            // Change the autogenerated foreign key names to more user-friendly ones
            attributes: [
                'id',
                ['userUsername', 'user'],
                ['teamName', 'team']
            ]
        })

        return res
            .status(200)
            .json(participants)
    } catch (err) {
        return next(new HTTP_Error(500, 'unexpected error', err))
    }
}

async function status(req, res, next) {
    try {
        // Find all the activities that need to be graded manually (of this event)
        const activitySets = await res.locals.event.getActivitySets({
            include: {
                model: Activity,
                attributes: ['id'],
                where: {
                    gradingType: 'judge'
                }
            }
        })
        // Reformat the activity ids
        let activityIDs = []
        activitySets.activities.forEach((activity) => {
            activityIDs.push(activity.id)
        })

        // Find all the submissions
        const submissions = await Submission.findAll({
            attributes: ['graded'],
            where: {
                // Only the submissions that are for activities that require manual grading
                activityId: activityIDs
            }
        })

        let total = 0
        let graded = 0
        // Loop through all submissions
        submissions.forEach((submission) => {
            total++
            if(submission.graded) graded++
        })

        return res
            .status(200)
            .json({"total_submissions": total, "graded": graded})
    } catch (err) {
        return next(new HTTP_Error(500, 'unexpected error', err))
    }
}

async function get_submissions_by_activity(req, res, next) {
    try {
        // Get all the submissions for this activity
        const submissions = await res.locals.activity.getSubmissions()

        return res
            .status(200)
            .json(submissions)
    } catch (err) {
        
    }
}

async function get_submissions_by_participant(req, res, next) {
    try {
        // Find all the activities that need to be graded manually (of this event)
        const activitySets = await res.locals.event.getActivitySets({
            include: {
                model: Activity,
                attributes: ['id'],
                where: {
                    gradingType: 'judge'
                }
            }
        })
        // Reformat the activity ids
        let activityIDs = []
        activitySets.activities.forEach((activity) => {
            activityIDs.push(activity.id)
        })

        const submissions = await res.locals.participant.getSubmissions({
            where: {
                activityId: activityIDs
            }
        })
        
        // Should only be one participant since id is primary key
        return res
            .status(200)
            .json(submissions)
    } catch (err) {
        return next(new HTTP_Error(500, 'unexpected error', err))
    }
}

async function grade_submission(req, res, next) {
    try {
        const rows_updated = await Submission.update({
            mark: req.body.mark,
            graded: true
        }, {
            where: {
                id: req.params.submissionID
            }
        })

        return res
            .status(201)
            .json({"message": `sucessfully graded submission ${req.params.submissionID}`})
    } catch (err) {
        
    }
}

module.exports.get_activities = get_activities
module.exports.get_participants = get_participants
module.exports.status = status
module.exports.get_submissions_by_activity = get_submissions_by_activity
module.exports.get_submissions_by_participant = get_submissions_by_participant
module.exports.grade_submission = grade_submission